Add support for separate metadata on upload.

diff --git a/scripts/pst b/scripts/pst
--- a/scripts/pst
+++ b/scripts/pst
@@ -34,12 +34,17 @@ API_CONTAINER=$CONTAINER_PREFIX-api
 WORKERS_CONTAINER=$CONTAINER_PREFIX-workers
 QUEUE_CONTAINER=$CONTAINER_PREFIX-queue
 
-VERSION=0.8.4
+VERSION=0.8.6
 
 buildContainers () {
 	cd pkg
 	docker build --rm -f beanstalkd.Dockerfile -t picstrata/beanstalkd:$VERSION -t picstrata/beanstalkd:latest .
 	npm run build
+	retVal=$?
+	if [ $retVal -ne 0 ]; then
+		echo "npm build error occurred."
+		exit $retVal
+	fi
 	docker build --rm -f api.Dockerfile -t picstrata/api:$VERSION -t picstrata/api:latest .
 	docker build --rm -f workers.Dockerfile -t picstrata/workers:$VERSION -t picstrata/workers:latest .
 	cd ../db 
